"""initial schema

Revision ID: 6f9bdf2a89c4
Revises: 
Create Date: 2026-06-06 14:10:34.684020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f9bdf2a89c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('loan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_name', sa.String(length=256), nullable=False),
    sa.Column('principal', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('annual_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('amort_type', sa.String(length=32), nullable=False),
    sa.Column('origination_date', sa.Date(), nullable=False),
    sa.Column('balloon_payment', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_cashflow',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('initial_investment', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('wacc', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('terminal_growth_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('reinvestment_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('security_type', sa.String(length=32), nullable=False),
    sa.Column('ipo_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_ticker'), ['ticker'], unique=True)

    op.create_table('cashflow_period',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=32), nullable=True),
    sa.Column('period_date', sa.Date(), nullable=True),
    sa.Column('cash_inflow', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('cash_outflow', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('net_cashflow', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('pv_factor', sa.Numeric(precision=14, scale=8), nullable=True),
    sa.Column('present_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('cumulative_cashflow', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project_cashflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cashflow_period', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cashflow_period_project_id'), ['project_id'], unique=False)

    op.create_table('financial_report',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=16), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.String(length=8), nullable=True),
    sa.Column('fiscal_quarter', sa.String(length=4), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_report_security_id'), ['security_id'], unique=False)

    op.create_table('holding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('intrinsic_value_at_purchase', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('margin_of_safety_at_purchase', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sold_date', sa.Date(), nullable=True),
    sa.Column('sold_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('realized_gain_loss', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holding_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holding_security_id'), ['security_id'], unique=False)

    op.create_table('intrinsic_value',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('calc_date', sa.Date(), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('book_value_per_share', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('eps_ttm', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_10yr_avg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_growth_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('terminal_growth_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('graham_number', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('ncav_per_share', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('dcf_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('earnings_power_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('intrinsic_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('market_price_at_calc', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('margin_of_safety_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intrinsic_value', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intrinsic_value_calc_date'), ['calc_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_intrinsic_value_security_id'), ['security_id'], unique=False)

    op.create_table('league_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('loan_amortization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('payment_number', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('principal_portion', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('interest_portion', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('remaining_balance', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('cumulative_principal', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('cumulative_interest', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_amortization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_amortization_loan_id'), ['loan_id'], unique=False)

    op.create_table('moving_average',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('calc_date', sa.Date(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('sma', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('ema', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('price_to_sma_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'calc_date', 'window_days', name='uq_ma_security_date_window')
    )
    with op.batch_alter_table('moving_average', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_moving_average_calc_date'), ['calc_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_moving_average_security_id'), ['security_id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('data_source', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'price_date', name='uq_price_history_security_date')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_price_date'), ['price_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_security_id'), ['security_id'], unique=False)

    op.create_table('project_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('npv', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('irr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('mirr', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('payback_period_years', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('discounted_payback_years', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('profitability_index', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('roi_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('terminal_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('calc_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project_cashflow.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('simulation_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('sim_type', sa.String(length=32), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('time_horizon_years', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('mu_annual_return', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('sigma_annual_vol', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('starting_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('risk_free_rate', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('benchmark_return', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('revenue_growth_low', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('revenue_growth_high', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('margin_low', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('margin_high', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('discount_rate_low', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('discount_rate_high', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_run_security_id'), ['security_id'], unique=False)

    op.create_table('valuation_ratio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('calc_date', sa.Date(), nullable=False),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ps_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('peg_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pe_times_pb', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('quick_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('cash_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('debt_to_assets', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('interest_coverage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('roa', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('roic', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('operating_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('net_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('fcf_yield', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('payout_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valuation_ratio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valuation_ratio_calc_date'), ['calc_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_valuation_ratio_security_id'), ['security_id'], unique=False)

    op.create_table('watchlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('target_buy_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('max_acceptable_pe', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('max_acceptable_pb', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('min_margin_of_safety', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('min_current_ratio', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('max_debt_to_equity', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('graham_criteria_notes', sa.Text(), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('added_date', sa.Date(), nullable=False),
    sa.Column('alert_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['security.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id')
    )
    op.create_table('balance_sheet',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('cash_and_equivalents', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('short_term_investments', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('accounts_receivable', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('inventory', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('other_current_assets', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('total_current_assets', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('property_plant_equipment_net', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('goodwill', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('intangible_assets', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('long_term_investments', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('other_non_current_assets', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('total_non_current_assets', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('accounts_payable', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('short_term_debt', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('current_portion_long_term_debt', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('other_current_liabilities', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('total_current_liabilities', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('long_term_debt', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('deferred_tax_liabilities', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('other_non_current_liabilities', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('total_non_current_liabilities', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('common_stock', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('additional_paid_in_capital', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('retained_earnings', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('treasury_stock', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('other_equity', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('total_liabilities_and_equity', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('net_current_assets', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('ncav', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['financial_report.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('cash_flow_statement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('net_income_cfs', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('depreciation_amortization', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('stock_based_compensation', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('changes_in_working_capital', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('other_operating_activities', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('cash_from_operations', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('capital_expenditures', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('acquisitions', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('purchase_of_investments', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('sale_of_investments', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('other_investing_activities', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('cash_from_investing', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('debt_issuance', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('debt_repayment', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('dividends_paid', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('share_buybacks', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('share_issuance', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('other_financing_activities', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('cash_from_financing', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('net_change_in_cash', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['financial_report.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('income_statement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('cost_of_goods_sold', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('research_and_development', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('selling_general_admin', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('other_operating_expenses', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('total_operating_expenses', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('ebit', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('interest_expense', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('interest_income', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('ebt', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('income_tax_expense', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('net_income_attributable', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('shares_outstanding_basic', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('shares_outstanding_diluted', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('eps_basic', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_diluted', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('dividends_per_share', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('period_months', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['financial_report.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_table('simulation_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('p5_outcome', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('p10_outcome', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('p25_outcome', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('p50_outcome', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('p75_outcome', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('p90_outcome', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('p95_outcome', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('mean_outcome', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('std_dev_outcome', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('min_outcome', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('max_outcome', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('prob_positive_return', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('prob_beats_benchmark', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('prob_loss_gt_20pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('prob_gain_gt_50pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('value_at_risk_5pct', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('percentile_distribution', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_result')
    op.drop_table('income_statement')
    op.drop_table('cash_flow_statement')
    op.drop_table('balance_sheet')
    op.drop_table('watchlist')
    with op.batch_alter_table('valuation_ratio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuation_ratio_security_id'))
        batch_op.drop_index(batch_op.f('ix_valuation_ratio_calc_date'))

    op.drop_table('valuation_ratio')
    with op.batch_alter_table('simulation_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_run_security_id'))

    op.drop_table('simulation_run')
    op.drop_table('project_metrics')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_security_id'))
        batch_op.drop_index(batch_op.f('ix_price_history_price_date'))

    op.drop_table('price_history')
    with op.batch_alter_table('moving_average', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_moving_average_security_id'))
        batch_op.drop_index(batch_op.f('ix_moving_average_calc_date'))

    op.drop_table('moving_average')
    with op.batch_alter_table('loan_amortization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_amortization_loan_id'))

    op.drop_table('loan_amortization')
    op.drop_table('league_members')
    with op.batch_alter_table('intrinsic_value', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intrinsic_value_security_id'))
        batch_op.drop_index(batch_op.f('ix_intrinsic_value_calc_date'))

    op.drop_table('intrinsic_value')
    with op.batch_alter_table('holding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holding_security_id'))
        batch_op.drop_index(batch_op.f('ix_holding_portfolio_id'))

    op.drop_table('holding')
    with op.batch_alter_table('financial_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_report_security_id'))

    op.drop_table('financial_report')
    with op.batch_alter_table('cashflow_period', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cashflow_period_project_id'))

    op.drop_table('cashflow_period')
    with op.batch_alter_table('security', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_ticker'))

    op.drop_table('security')
    op.drop_table('project_cashflow')
    op.drop_table('portfolio')
    op.drop_table('loan')
    op.drop_table('leagues')
    # ### end Alembic commands ###
